import { Category } from '../../../core/models';

export const MOCK_CATEGORIES: Category[] = [
  // ── Electronics ──
  {
    id: 'cat-001',
    nameEn: 'Electronics',
    nameAr: 'إلكترونيات',
    descEn: 'Electronic devices and accessories',
    descAr: 'الأجهزة الإلكترونية والإكسسوارات',
    parentId: null,
    pricingMethod: 'fixed',
    salesStrategy: 'fifo',
    inactive: false,
    images: [
      { id: 'img-001', url: 'https://placehold.co/120x120/4F46E5/white?text=Electronics', destination: 'web', isDefault: true },
    ],
    createdAt: new Date('2025-01-15'),
    updatedAt: new Date('2025-06-10'),
  },
  {
    id: 'cat-002',
    nameEn: 'Smartphones',
    nameAr: 'هواتف ذكية',
    descEn: 'Mobile phones and smartphones',
    descAr: 'الهواتف المحمولة والهواتف الذكية',
    parentId: 'cat-001',
    pricingMethod: 'fixed',
    salesStrategy: 'fifo',
    inactive: false,
    images: [],
    createdAt: new Date('2025-02-01'),
    updatedAt: new Date('2025-06-10'),
  },
  {
    id: 'cat-003',
    nameEn: 'Laptops',
    nameAr: 'أجهزة لابتوب',
    descEn: 'Notebook and laptop computers',
    descAr: 'أجهزة الكمبيوتر المحمولة',
    parentId: 'cat-001',
    pricingMethod: 'fixed',
    salesStrategy: 'fifo',
    inactive: false,
    images: [],
    createdAt: new Date('2025-02-05'),
    updatedAt: new Date('2025-06-10'),
  },
  {
    id: 'cat-004',
    nameEn: 'Tablets',
    nameAr: 'أجهزة لوحية',
    descEn: 'Tablet devices and e-readers',
    descAr: 'الأجهزة اللوحية وأجهزة القراءة',
    parentId: 'cat-001',
    pricingMethod: 'fixed',
    salesStrategy: 'fifo',
    inactive: false,
    images: [],
    createdAt: new Date('2025-02-10'),
    updatedAt: new Date('2025-06-10'),
  },

  // ── Furniture ──
  {
    id: 'cat-010',
    nameEn: 'Furniture',
    nameAr: 'أثاث',
    descEn: 'Home and office furniture',
    descAr: 'أثاث المنزل والمكتب',
    parentId: null,
    pricingMethod: 'average',
    salesStrategy: 'fifo',
    inactive: false,
    images: [
      { id: 'img-010', url: 'https://placehold.co/120x120/10B981/white?text=Furniture', destination: 'web', isDefault: true },
    ],
    createdAt: new Date('2025-01-20'),
    updatedAt: new Date('2025-05-15'),
  },
  {
    id: 'cat-011',
    nameEn: 'Office Chairs',
    nameAr: 'كراسي مكتبية',
    descEn: 'Ergonomic and standard office chairs',
    descAr: 'كراسي المكتب المريحة والعادية',
    parentId: 'cat-010',
    pricingMethod: 'average',
    salesStrategy: 'fifo',
    inactive: false,
    images: [],
    createdAt: new Date('2025-02-15'),
    updatedAt: new Date('2025-05-15'),
  },
  {
    id: 'cat-012',
    nameEn: 'Desks',
    nameAr: 'مكاتب',
    descEn: 'Standing desks and work tables',
    descAr: 'مكاتب الوقوف وطاولات العمل',
    parentId: 'cat-010',
    pricingMethod: 'average',
    salesStrategy: 'fifo',
    inactive: false,
    images: [],
    createdAt: new Date('2025-02-20'),
    updatedAt: new Date('2025-05-15'),
  },

  // ── Clothing ──
  {
    id: 'cat-020',
    nameEn: 'Clothing',
    nameAr: 'ملابس',
    descEn: 'Apparel and fashion items',
    descAr: 'الملابس والأزياء',
    parentId: null,
    pricingMethod: 'fixed',
    salesStrategy: 'filo',
    inactive: false,
    images: [
      { id: 'img-020', url: 'https://placehold.co/120x120/F59E0B/white?text=Clothing', destination: 'web', isDefault: true },
    ],
    createdAt: new Date('2025-03-01'),
    updatedAt: new Date('2025-07-01'),
  },
  {
    id: 'cat-021',
    nameEn: "Men's Wear",
    nameAr: 'ملابس رجالية',
    descEn: "Men's clothing and accessories",
    descAr: 'ملابس وإكسسوارات رجالية',
    parentId: 'cat-020',
    pricingMethod: 'fixed',
    salesStrategy: 'filo',
    inactive: false,
    images: [],
    createdAt: new Date('2025-03-05'),
    updatedAt: new Date('2025-07-01'),
  },
  {
    id: 'cat-022',
    nameEn: "Women's Wear",
    nameAr: 'ملابس نسائية',
    descEn: "Women's clothing and accessories",
    descAr: 'ملابس وإكسسوارات نسائية',
    parentId: 'cat-020',
    pricingMethod: 'fixed',
    salesStrategy: 'filo',
    inactive: false,
    images: [],
    createdAt: new Date('2025-03-10'),
    updatedAt: new Date('2025-07-01'),
  },
  {
    id: 'cat-023',
    nameEn: "Kids' Wear",
    nameAr: 'ملابس أطفال',
    descEn: "Children's clothing for all ages",
    descAr: 'ملابس الأطفال لجميع الأعمار',
    parentId: 'cat-020',
    pricingMethod: 'fixed',
    salesStrategy: 'filo',
    inactive: false,
    images: [],
    createdAt: new Date('2025-03-15'),
    updatedAt: new Date('2025-07-01'),
  },

  // ── Food & Beverages ──
  {
    id: 'cat-030',
    nameEn: 'Food & Beverages',
    nameAr: 'أغذية ومشروبات',
    descEn: 'Food products and drinks',
    descAr: 'المنتجات الغذائية والمشروبات',
    parentId: null,
    pricingMethod: 'actual_cost',
    salesStrategy: 'fefo',
    inactive: false,
    images: [
      { id: 'img-030', url: 'https://placehold.co/120x120/EF4444/white?text=F%26B', destination: 'web', isDefault: true },
    ],
    createdAt: new Date('2025-04-01'),
    updatedAt: new Date('2025-08-01'),
  },
  {
    id: 'cat-031',
    nameEn: 'Snacks',
    nameAr: 'وجبات خفيفة',
    descEn: 'Chips, crackers, and snack items',
    descAr: 'رقائق ومقرمشات ووجبات خفيفة',
    parentId: 'cat-030',
    pricingMethod: 'actual_cost',
    salesStrategy: 'fefo',
    inactive: false,
    images: [],
    createdAt: new Date('2025-04-05'),
    updatedAt: new Date('2025-08-01'),
  },
  {
    id: 'cat-032',
    nameEn: 'Drinks',
    nameAr: 'مشروبات',
    descEn: 'Soft drinks, juices, and water',
    descAr: 'مشروبات غازية وعصائر ومياه',
    parentId: 'cat-030',
    pricingMethod: 'actual_cost',
    salesStrategy: 'fefo',
    inactive: true,
    images: [],
    createdAt: new Date('2025-04-10'),
    updatedAt: new Date('2025-08-01'),
  },

  // ── Office Supplies ──
  {
    id: 'cat-040',
    nameEn: 'Office Supplies',
    nameAr: 'مستلزمات مكتبية',
    descEn: 'Stationery and office essentials',
    descAr: 'القرطاسية ومستلزمات المكتب',
    parentId: null,
    pricingMethod: 'average',
    salesStrategy: 'fifo',
    inactive: false,
    images: [
      { id: 'img-040', url: 'https://placehold.co/120x120/6366F1/white?text=Office', destination: 'web', isDefault: true },
    ],
    createdAt: new Date('2025-05-01'),
    updatedAt: new Date('2025-09-01'),
  },
  {
    id: 'cat-041',
    nameEn: 'Paper Products',
    nameAr: 'منتجات ورقية',
    descEn: 'Notebooks, printing paper, and envelopes',
    descAr: 'دفاتر وأوراق طباعة ومظاريف',
    parentId: 'cat-040',
    pricingMethod: 'average',
    salesStrategy: 'fifo',
    inactive: false,
    images: [],
    createdAt: new Date('2025-05-05'),
    updatedAt: new Date('2025-09-01'),
  },
  {
    id: 'cat-042',
    nameEn: 'Pens & Writing',
    nameAr: 'أقلام وأدوات كتابة',
    descEn: 'Pens, pencils, and markers',
    descAr: 'أقلام حبر وأقلام رصاص وأقلام تحديد',
    parentId: 'cat-040',
    pricingMethod: 'average',
    salesStrategy: 'fifo',
    inactive: false,
    images: [],
    createdAt: new Date('2025-05-10'),
    updatedAt: new Date('2025-09-01'),
  },

  // ── Beauty & Health ──
  {
    id: 'cat-050',
    nameEn: 'Beauty & Health',
    nameAr: 'جمال وصحة',
    descEn: 'Personal care and beauty products',
    descAr: 'منتجات العناية الشخصية والجمال',
    parentId: null,
    pricingMethod: 'fixed',
    salesStrategy: 'fefo',
    inactive: false,
    images: [
      { id: 'img-050', url: 'https://placehold.co/120x120/EC4899/white?text=Beauty', destination: 'web', isDefault: true },
    ],
    createdAt: new Date('2025-06-01'),
    updatedAt: new Date('2025-10-01'),
  },
  {
    id: 'cat-051',
    nameEn: 'Skincare',
    nameAr: 'عناية بالبشرة',
    descEn: 'Moisturizers, serums, and sunscreens',
    descAr: 'مرطبات وسيرومات وواقيات شمس',
    parentId: 'cat-050',
    pricingMethod: 'fixed',
    salesStrategy: 'fefo',
    inactive: false,
    images: [],
    createdAt: new Date('2025-06-05'),
    updatedAt: new Date('2025-10-01'),
  },
  {
    id: 'cat-052',
    nameEn: 'Haircare',
    nameAr: 'عناية بالشعر',
    descEn: 'Shampoos, conditioners, and styling products',
    descAr: 'شامبوهات وبلسمات ومنتجات تصفيف',
    parentId: 'cat-050',
    pricingMethod: 'fixed',
    salesStrategy: 'fefo',
    inactive: true,
    images: [],
    createdAt: new Date('2025-06-10'),
    updatedAt: new Date('2025-10-01'),
  },
];
